### ISSUE TITLE
Pipeline Memory

### ISSUE THREAD

**Issue by yairhaimo** [WeAreAigur/client#21]
# Pipeline Memory

Retain information between Pipeline executions

## Limitations
- Serverless Functions must save externally - Serverless/Edge functions cant rely on saving the memory in the pipeline itself since it will be destroyed according to the function's lifecycle.

## What to Save

- Define explicitly what to save between runs

```ts
aigur.pipeline.create<{subject: string}, { joke: string }>(
  {
    id: 'jokegpt',
    flow: (flow) =>
      flow
        .node(replaceString, ({ input, memory }) => ({ // <-- memory is available to the nodes
          text: `${input.subject}${memory?.subject ? ` and ${memory.subject}` : ''}`,
          modifier: 'tell me a joke about $(text)$',
        }))
        .node(gpt3Prediction, ({ prev }) => ({
          prompt: prev.text,
        }))
        .output(({ prev }) => ({
          joke: prev.text,
        })),
    retainMemory: ({ input, nodes, output, memory }) => ({ // <-- returns an object that will be saved in the memory
      subject: input.subject,
    })
  }
);
```

## Where to Save

```ts
const aigur = createClient({
    apiKeys: {},
    memorySave: (pipeline: Pipeline, memoryToSave: Record<string, any>): void => {
        redis.set(pipeline.id, memoryToSave);
    },
    memoryLoad: (pipeline: Pipeline): Promise<Record<string, any>> => {
        return redis.get(pipeline.id);
    }
});
```

## Special Cases
- To save streams we need to call the `memorySave` method after the stream is done
  - Stream must be typed in order for us to know the final output type

## Typing

A third generic parameter can be passed to the pipeline to define the type of the memory

```ts
aigur.pipeline.create<{subject: string}, { joke: string }, {subject: string}>(
```

## Advanced RetainMemory

In some cases we want to transform the memory before saving it.
Maybe we can have an api to run it through a node/pipeline before saving?

**Use case**: summarize a conversation before saving it to memory
This could be done without a special `RetainMemory` with the future `split` node:
- Run the main flow of the pipeline and split to a summary node and use its output when retaining memory

**Comment by Iftahh** [comment]
Regarding "Where to Save" -

1. your example doesn't feature different memory for different users (or different sessions of the same user) - is this on purpose for simplicity of the example?
I think this is a most useful feature of a memory component.

2. instead of supplying `memorySave` and `memoryLoad` functions to the client - I think its better to create a Memory object (with `save` and `load`  interface) and pass this object to the client, so one could plug-and-play different memory solutions.

eg. 
```javascript
const aigur = createClient({
    apiKeys: {},
    memory: new RedisMemory()      //  or DatabaseMemory,  etc..
});
```

---
Regarding "What to Save"  -

I'm pondering if `retainMemory` that "pulls" information from the pipeline into memory is the best approach.
I'm thinking about the potential to reuse nodes or sections of pipelines - I think it would be easier to reuse nodes if they come together with the relevant snippet that writes and reads the memory.

Something like - `updateMemory` inside a node description

```javascript
flow: (flow) =>
      flow
        .node(replaceString, ({ input, memory }) => ({ // <-- memory is available to the nodes
          text: `\n\nHistory: \n${memory.history} \n\n Human: ${input.text} \n\n Bot: `,
          modifier: 'You are a funny sarcastic bot AI, talking to a human. $(text)$',
          updateMemory: () => { appendToChatHistory(memory.history, input.text) }
        }))
        .node(gpt3Prediction, ({ prev }) => ({
          prompt: prev.text,
        }))
        .output(({ prev }) => ({
          botResponse: prev.text,
        })),

**Comment by yairhaimo** [comment]
1. Right now you can manage it manually by adding a property (e.g `userId`) to the Pipeline input and then use that when saving the memory. We can think about a more friendly way in the future.
2. Good call. I agree.
3. I wonder if it will help or hinder reusing Nodes - in one Pipeline I want the Node to update the memory but in another I dont. An optional `updateMemory` function at the Node level in addition to an `updateMemory` at the Pipeline level will give you the flexibility to configure it however you want.

**Comment by yairhaimo** [comment]
I just merged Pipeline Memory. I adopted all your comments.
Going to write the docs now but the API is:
```ts
createClient({
  apiKeys: {},
  memoryManager: createUpstashRedisMemory(), // example memory manager
});

flow: (flow) =>
      flow
        .node(
           someNode, 
           ({ input, prev, nodes, memory }) => ({ }),
           // this third parameter is the "updateMemory" function, whatever it returns is saved
           ({ input, output, nodes, memory, prev }) => ({  
             previousMessage: output.text // <-- can access the node's output, even if its a stream
          })
        )
```
